/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'timestamp' : bigint,
}
export interface CheckupReminder {
  'nextDueDate' : bigint,
  'studentPrincipal' : Principal,
  'lastCheckupDate' : bigint,
}
export interface Counselor {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'photoUrl' : string,
  'isActive' : boolean,
  'specialty' : string,
  'availability' : string,
}
export interface StudentProfile {
  'principal' : Principal,
  'assignedCounselorId' : [] | [bigint],
  'name' : string,
  'email' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCounselor' : ActorMethod<[Counselor], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCounselor' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCounselor' : ActorMethod<[bigint], Counselor>,
  'getMessages' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getMyAssignment' : ActorMethod<[], [] | [bigint]>,
  'getMyProfile' : ActorMethod<[], StudentProfile>,
  'getMyReminder' : ActorMethod<[], CheckupReminder>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeUser' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCounselors' : ActorMethod<[], Array<Counselor>>,
  'registerStudent' : ActorMethod<[string, string], undefined>,
  'removeCounselor' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleCounselors' : ActorMethod<[], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'setLastCheckup' : ActorMethod<[bigint], undefined>,
  'updateCounselor' : ActorMethod<[Counselor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
