/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Counselor = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'specialty' : IDL.Text,
  'availability' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const StudentProfile = IDL.Record({
  'principal' : IDL.Principal,
  'assignedCounselorId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CheckupReminder = IDL.Record({
  'nextDueDate' : IDL.Int,
  'studentPrincipal' : IDL.Principal,
  'lastCheckupDate' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCounselor' : IDL.Func([Counselor], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCounselor' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCounselor' : IDL.Func([IDL.Nat], [Counselor], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(ChatMessage)], ['query']),
  'getMyAssignment' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getMyProfile' : IDL.Func([], [StudentProfile], ['query']),
  'getMyReminder' : IDL.Func([], [CheckupReminder], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeUser' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCounselors' : IDL.Func([], [IDL.Vec(Counselor)], ['query']),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeCounselor' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleCounselors' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'setLastCheckup' : IDL.Func([IDL.Int], [], []),
  'updateCounselor' : IDL.Func([Counselor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Counselor = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'specialty' : IDL.Text,
    'availability' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const StudentProfile = IDL.Record({
    'principal' : IDL.Principal,
    'assignedCounselorId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const CheckupReminder = IDL.Record({
    'nextDueDate' : IDL.Int,
    'studentPrincipal' : IDL.Principal,
    'lastCheckupDate' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCounselor' : IDL.Func([Counselor], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCounselor' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCounselor' : IDL.Func([IDL.Nat], [Counselor], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getMyAssignment' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getMyProfile' : IDL.Func([], [StudentProfile], ['query']),
    'getMyReminder' : IDL.Func([], [CheckupReminder], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeUser' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCounselors' : IDL.Func([], [IDL.Vec(Counselor)], ['query']),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeCounselor' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleCounselors' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'setLastCheckup' : IDL.Func([IDL.Int], [], []),
    'updateCounselor' : IDL.Func([Counselor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
